nome = input('Me dia seu nome: ')
print('Analisando seu lindo nome...')
print('Seu nome só com letras maisculas é: {}'.format(nome.upper()))
print('Seu nome em minusculas é: {}'.format(nome.lower()))
junto = nome.split()
juntom = len(''.join(junto))
print('Seu nome tem {} letras'.format(juntom))
juntoum = len(''.join(junto[0]))
print('Seu primeiro nome tem {} letras '.format(juntoum))
